---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sightran/public_html/
    - /bin/cp -R apps $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R sightra $DEPLOYPATH
    - /bin/cp manage.py $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH